## Seeds

- Setting random seeds helps us attain reproducability even if a piece of code requires randomness.
- Seeds need to be set in different ways depending on the library that uses randomness.

In [10]:
# In "Base" random package...

import random

random.seed(0)

print(random.random())

0.8444218515250481


In [11]:
# In Numpy...

import numpy as np

np.random.seed(0)

a = np.random.randint(0, 100, size = (10, 10))

print(a)

[[44 47 64 67 67  9 83 21 36 87]
 [70 88 88 12 58 65 39 87 46 88]
 [81 37 25 77 72  9 20 80 69 79]
 [47 64 82 99 88 49 29 19 19 14]
 [39 32 65  9 57 32 31 74 23 35]
 [75 55 28 34  0  0 36 53  5 38]
 [17 79  4 42 58 31  1 65 41 57]
 [35 11 46 82 91  0 14 99 53 12]
 [42 84 75 68  6 68 47  3 76 52]
 [78 15 20 99 58 23 79 13 85 48]]


In [12]:
# In PyTorch...

import torch

torch.random.manual_seed(0)

a = torch.randint(0, 100, (10, 10))

print(a)

tensor([[44, 39, 33, 60, 63, 79, 27,  3, 97, 83],
        [ 1, 66, 56, 99, 78, 76, 56, 68, 94, 33],
        [26, 19, 91, 54, 24, 41, 69, 69, 49, 80],
        [81, 12, 63, 60, 95, 85, 22, 99, 11, 88],
        [78, 43, 96, 89, 71, 57, 83, 95, 82, 71],
        [40, 69, 73, 41, 11, 80,  3,  6, 76, 27],
        [99, 26, 63, 74, 75,  0, 18, 32, 68, 12],
        [77, 45, 10, 80, 48, 21, 19, 16, 81, 90],
        [82, 19, 44, 33, 69, 63,  9, 33, 19, 78],
        [35, 83, 22, 58, 35, 16, 46, 35, 77, 12]])


## JSON

- JSON is a file format that allows us to store hierarchical data.
- JSON stands for **J**ava**s**cript **O**bject **N**otation; Javascript uses objects that are formatted the same way as JSON files, but they are not separate files like JSON.
- The hierarchical way in which JSON stores data is very similar to the way Python stores dictionaries.
  - The only difference is that Python's `None` becomes Javascripts's `null` and Python's `True`/`False` become `true`/`false`, respectively.

In [13]:
# Python dictionary containing hierarchical information about publication(s)

obj = {
    "glossary": {
        "title": "example glossary",
        "GlossDiv": {
            "title": "S",
            "GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
                    "SortAs": "SGML",
                    "GlossTerm": "Standard Generalized Markup Language",
                    "Acronym": "SGML",
                    "Abbrev": "ISO 8879:1986",
                    "GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
                        "GlossSeeAlso": ["GML", "XML"],
                    },
                    "GlossSee": None,
                    "sample-bool": True,
                }
            },
        },
    }
}


In [14]:
# Javascript object (below) containing the same hierarchical information about publication(s).


```javascript
obj = {
    "glossary": {
        "title": "example glossary",
        "GlossDiv": {
            "title": "S",
            "GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
                    "SortAs": "SGML",
                    "GlossTerm": "Standard Generalized Markup Language",
                    "Acronym": "SGML",
                    "Abbrev": "ISO 8879:1986",
                    "GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
                        "GlossSeeAlso": ["GML", "XML"]
                    },
                    "GlossSee": null, // None >> null
                    "sample-bool": true // True >> true
                }
            }
        }
    }
}
```


You can see an actual JSON file in `./sample.json`